# Generated by Django 5.0.14 on 2026-01-31 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scale_type', models.CharField(choices=[('scl90_sample', 'SCL-90（示例）'), ('sas_sample', 'SAS（示例）'), ('sds_sample', 'SDS（示例）'), ('custom', '自定义')], default='custom', max_length=32)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '问卷模板',
                'verbose_name_plural': '问卷模板',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.college')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.questionnairetemplate')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.questionnaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '问卷作答',
                'verbose_name_plural': '问卷作答',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionnaireresponse',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'student'), name='uniq_response_questionnaire_student'),
        ),
    ]
