# Generated by Django 5.0.14 on 2026-01-31 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='干预建议', max_length=120)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已推送'), ('in_progress', '进行中'), ('done', '已完成')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentresult')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '干预建议',
                'verbose_name_plural': '干预建议',
                'ordering': ['-id'],
            },
        ),
    ]
