# Generated by Django 5.0.14 on 2026-01-31 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=16)),
                ('predicted_risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='surveys.questionnaireresponse')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=16)),
                ('message', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assessments.assessmentresult')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '风险预警',
                'verbose_name_plural': '风险预警',
                'ordering': ['-id'],
            },
        ),
    ]
